### ISSUE TITLE
Problem about config of storage node

### ISSUE THREAD

**Issue by RicardoZhy1215** [eniac/TELEPORT#2]
Hi, there, I have run the processor node and memory node successfully but when I config the storage node of Teleport,  I encounter a problem. Firtsly, I run a  'maek' command in the 'linux_modules' directory,  and then run "source run.sh" command in the same directory. It means insert modules. But it reports 
"insmod TELEPORT/linux-modules/fit/fit.ko 
insmod: ERROR: could not insert module TELEPORT/linux-modules/fit/fit.ko: Unknown symbol in module
root@node-2:/storage# insmod storage.ko
insmod: ERROR: could not load module storage.ko: No such file or directory
root@node-2:/storage# insmod TELEPORT/linux-modules/storage/storage.ko 
insmod: ERROR: could not insert module TELEPORT/linux-modules/storage/storage.ko: Unknown symbol in module".
Do you have ideas to solve this problem?  My kernel version is 3.11.1 and have installed infiniband drivers.
I really appreciate you support!

**Comment by RicardoZhy1215** [comment]
And I want to know that Teleprot is based on which kernel version?

**Comment by cxinyic** [comment]
Hi Recardo,

Thanks for the question. Since Teleport is partially based on LegoOS, we are testing with kernel version 3.11.1.

**Comment by cxinyic** [comment]
For the first question, can you give me a screen shot about your linux_modules directory after you do "make" command?
Another small thing is that you might need to run storage node first, then run compute & memory node.

**Comment by RicardoZhy1215** [comment]
Hi，many thanks for your quick response. here is the output of the 'make' command output in the 'linux_modules' directory
<img width="132" alt="output" src="https://github.com/eniac/TELEPORT/assets/66266662/21b6be4d-49a5-4a58-8863-58f8b2d0175f">

root@node-0:/storage/project/TELEPORT/linux-modules# make
make -C /storage/project/TELEPORT/linux-modules/fit
make[1]: Entering directory `/storage/project/TELEPORT/linux-modules/fit'
make -C /lib/modules/3.11.1/build M=/storage/project/TELEPORT/linux-modules/fit modules
make[2]: Entering directory `/usr/src/linux-3.11.1'
  CC [M]  /storage/project/TELEPORT/linux-modules/fit/fit_ibapi.o
  CC [M]  /storage/project/TELEPORT/linux-modules/fit/fit_internal.o
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c: In function ‘fit_init_ctx’:
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:292:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   struct ib_qp_attr attr;
   ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:322:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   struct ib_qp_attr attr1 = {
   ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c: In function ‘fit_post_receives_message_with_buffer’:
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:624:3: warning: format ‘%p’ expects argument of type ‘void *’, but argument 4 has type ‘uintptr_t’ [-Wformat=]
   printk(KERN_CRIT "%s pristruct %p header %p buf %p msg %p byf %p\n", __func__, p_r_i_struct, p_r_i_struct->header, buf, p_r_i_struct->msg, addr);
   ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:624:3: warning: format ‘%p’ expects argument of type ‘void *’, but argument 6 has type ‘uintptr_t’ [-Wformat=]
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:624:3: warning: format ‘%p’ expects argument of type ‘void *’, but argument 7 has type ‘uintptr_t’ [-Wformat=]
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:632:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   struct ib_recv_wr wr, *bad_wr = NULL;
   ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:643:5: warning: format ‘%p’ expects argument of type ‘void *’, but argument 4 has type ‘uintptr_t’ [-Wformat=]
     __func__, header, header_addr, buf, addr, ctx->proc->lkey);
     ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:643:5: warning: format ‘%p’ expects argument of type ‘void *’, but argument 6 has type ‘uintptr_t’ [-Wformat=]
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c: In function ‘fit_internal_poll_sendcq’:
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:930:5: warning: "SEPARATE_SEND_POLL_THREAD" is not defined [-Wundef]
 #if SEPARATE_SEND_POLL_THREAD
     ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c: In function ‘fit_send_message_with_rdma_write_with_imm_request’:
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:996:1: warning: label ‘retry_send_imm_request’ defined but not used [-Wunused-label]
 retry_send_imm_request:
 ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:992:6: warning: unused variable ‘flag’ [-Wunused-variable]
  int flag=0;
      ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c: In function ‘fit_receive_message’:
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1168:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   pass->msg = (char*)node_id; //(char*)current_hash_ptr;
               ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1094:6: warning: unused variable ‘ret’ [-Wunused-variable]
  int ret = 0;
      ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c: In function ‘fit_reply_message’:
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1187:20: warning: unused variable ‘ibd’ [-Wunused-variable]
  struct ib_device *ibd = (struct ib_device *)ctx->context;
                    ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1186:8: warning: unused variable ‘real_addr’ [-Wunused-variable]
  void *real_addr;
        ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1185:16: warning: unused variable ‘phys_addr’ [-Wunused-variable]
  unsigned long phys_addr;
                ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c: In function ‘fit_poll_cq’:
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1523:19: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       recv->msg = (char *)offset;
                   ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1542:7: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘__be32’ [-Wformat=]
       pr_err("Unknown wc[i].ex.imm_data: %#lx\n", wc[i].ex.imm_data);
       ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1546:6: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘int’ [-Wformat=]
      pr_err("Unknown wc_flags %#lx\n", wc[i].wc_flags);
      ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1450:31: warning: unused variable ‘descriptor’ [-Wunused-variable]
  struct imm_message_metadata *descriptor; 
                               ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1449:25: warning: unused variable ‘opcode’ [-Wunused-variable]
  int semaphore, length, opcode;
                         ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c: In function ‘waiting_queue_handler’:
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1616:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
      int target_node = (int) new_request->msg; //ptr->node;
                        ^
/storage/project/TELEPORT/linux-modules/fit/fit_internal.c:1642:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
      last_ack = (int)new_request->msg; 
                 ^
  CC [M]  /storage/project/TELEPORT/linux-modules/fit/fit_machine.o
  LD [M]  /storage/project/TELEPORT/linux-modules/fit/fit.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /storage/project/TELEPORT/linux-modules/fit/fit.mod.o
  LD [M]  /storage/project/TELEPORT/linux-modules/fit/fit.ko
make[2]: Leaving directory `/usr/src/linux-3.11.1'
-e \e[00;31m****
****    WARNING
****       Compiled with -g option
-e ****\e[00m
make[1]: Leaving directory `/storage/project/TELEPORT/linux-modules/fit'
make -C /storage/project/TELEPORT/linux-modules/storage
make[1]: Entering directory `/storage/project/TELEPORT/linux-modules/storage'
make -C /lib/modules/3.11.1/build M=/storage/project/TELEPORT/linux-modules/storage modules
make[2]: Entering directory `/usr/src/linux-3.11.1'
  CC [M]  /storage/project/TELEPORT/linux-modules/storage/core.o
  CC [M]  /storage/project/TELEPORT/linux-modules/storage/handlers.o
  CC [M]  /storage/project/TELEPORT/linux-modules/storage/file_ops.o
  CC [M]  /storage/project/TELEPORT/linux-modules/storage/replica.o
  CC [M]  /storage/project/TELEPORT/linux-modules/storage/stat.o
  LD [M]  /storage/project/TELEPORT/linux-modules/storage/storage.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /storage/project/TELEPORT/linux-modules/storage/storage.mod.o
  LD [M]  /storage/project/TELEPORT/linux-modules/storage/storage.ko
make[2]: Leaving directory `/usr/src/linux-3.11.1'
make[1]: Leaving directory `/storage/project/TELEPORT/linux-modules/storage'
make -C /storage/project/TELEPORT/linux-modules/monitor
make[1]: Entering directory `/storage/project/TELEPORT/linux-modules/monitor'
make -C /storage/project/TELEPORT/linux-modules/monitor/gmm
make[2]: Entering directory `/storage/project/TELEPORT/linux-modules/monitor/gmm'
make -C /lib/modules/3.11.1/build M=/storage/project/TELEPORT/linux-modules/monitor/gmm modules
make[3]: Entering directory `/usr/src/linux-3.11.1'
  CC [M]  /storage/project/TELEPORT/linux-modules/monitor/gmm/lego_gmm.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /storage/project/TELEPORT/linux-modules/monitor/gmm/lego_gmm.mod.o
  LD [M]  /storage/project/TELEPORT/linux-modules/monitor/gmm/lego_gmm.ko
make[3]: Leaving directory `/usr/src/linux-3.11.1'
make[2]: Leaving directory `/storage/project/TELEPORT/linux-modules/monitor/gmm'
make -C /storage/project/TELEPORT/linux-modules/monitor/gpm
make[2]: Entering directory `/storage/project/TELEPORT/linux-modules/monitor/gpm'
make -C /lib/modules/3.11.1/build M=/storage/project/TELEPORT/linux-modules/monitor/gpm modules
make[3]: Entering directory `/usr/src/linux-3.11.1'
  CC [M]  /storage/project/TELEPORT/linux-modules/monitor/gpm/lego_gpm.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /storage/project/TELEPORT/linux-modules/monitor/gpm/lego_gpm.mod.o
  LD [M]  /storage/project/TELEPORT/linux-modules/monitor/gpm/lego_gpm.ko
make[3]: Leaving directory `/usr/src/linux-3.11.1'
make[2]: Leaving directory `/storage/project/TELEPORT/linux-modules/monitor/gpm'
make -C /storage/project/TELEPORT/linux-modules/monitor/gum
make[2]: Entering directory `/storage/project/TELEPORT/linux-modules/monitor/gum'
make -C /lib/modules/3.11.1/build M=/storage/project/TELEPORT/linux-modules/monitor/gum modules
make[3]: Entering directory `/usr/src/linux-3.11.1'
  CC [M]  /storage/project/TELEPORT/linux-modules/monitor/gum/lego_gum.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /storage/project/TELEPORT/linux-modules/monitor/gum/lego_gum.mod.o
  LD [M]  /storage/project/TELEPORT/linux-modules/monitor/gum/lego_gum.ko
make[3]: Leaving directory `/usr/src/linux-3.11.1'
make[2]: Leaving directory `/storage/project/TELEPORT/linux-modules/monitor/gum'
make -C /storage/project/TELEPORT/linux-modules/monitor/gm_dispatcher
make[2]: Entering directory `/storage/project/TELEPORT/linux-modules/monitor/gm_dispatcher'
make -C /lib/modules/3.11.1/build M=/storage/project/TELEPORT/linux-modules/monitor/gm_dispatcher modules
make[3]: Entering directory `/usr/src/linux-3.11.1'
  CC [M]  /storage/project/TELEPORT/linux-modules/monitor/gm_dispatcher/lego_gm_dispatcher.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /storage/project/TELEPORT/linux-modules/monitor/gm_dispatcher/lego_gm_dispatcher.mod.o
  LD [M]  /storage/project/TELEPORT/linux-modules/monitor/gm_dispatcher/lego_gm_dispatcher.ko
make[3]: Leaving directory `/usr/src/linux-3.11.1'
make[2]: Leaving directory `/storage/project/TELEPORT/linux-modules/monitor/gm_dispatcher'
make[1]: Leaving directory `/storage/project/TELEPORT/linux-modules/monitor'

**Comment by RicardoZhy1215** [comment]
> For the first question, can you give me a screen shot about your linux_modules directory after you do "make" command? Another small thing is that you might need to run storage node first, then run compute & memory node.

So basically, following the instructions in the LegoOS, we don't need to reboot the storage node, right?  we just need to run "insmod fit.ko" and "insmod storage.ko".

**Comment by RicardoZhy1215** [comment]
We are still struggling with the storage node problem. Could you please help check out where our configurations might be wrong or provide some instructions on this?

**Comment by cxinyic** [comment]
Sorry for the late. Since there are some changes in our lab testbed, I am trying to reproduce it on cloudlab and I will try to respond soon.

**Comment by RicardoZhy1215** [comment]
Many thanks for your response, I also test the Teleport on the cloudlab with upenn's network profile created by Yifan Cai. I run the 1P-1M model of LegoOS, it works. But when I try 1P-1M-1S model for Teleport, the storage node doesn't work and has problems as I posted before. Many thanks for your help!
